
daemon=600				# NEED to upgrade from 300->600
syslog=yes				# log update msgs to syslog
pid=/var/run/ddclient/ddclient.pid	# record PID in file.
ssl=yes 				# use ssl-support.  Works with

use=web, web=checkip.dyndns.org/, web-skip='IP Address' # found after IP Address

##
## CloudFlare (www.cloudflare.com)
##
protocol=cloudflare,        \
zone=example.com,            \
ttl=120,                      \
login=token,     \ # Only needed if you are using your global API key. If you are using an API token, set it to "token" (without double quotes).
password=long_api_key_string   \ # This is either your global API key, or an API token. If you are using an API token, it must have the permissions "Zone - DNS - Edit" and "Zone - Zone - Read". The Zone resources must be "Include - All zones".
subdomain1.example.com,subdomain2.example.com


